// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Record.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Record_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Record_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Record_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Record_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Record_2eproto;
class Record;
struct RecordDefaultTypeInternal;
extern RecordDefaultTypeInternal _Record_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Record* Arena::CreateMaybeMessage<::Record>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Record final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Record) */ {
 public:
  inline Record() : Record(nullptr) {}
  ~Record() override;
  explicit PROTOBUF_CONSTEXPR Record(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Record(const Record& from);
  Record(Record&& from) noexcept
    : Record() {
    *this = ::std::move(from);
  }

  inline Record& operator=(const Record& from) {
    CopyFrom(from);
    return *this;
  }
  inline Record& operator=(Record&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Record& default_instance() {
    return *internal_default_instance();
  }
  static inline const Record* internal_default_instance() {
    return reinterpret_cast<const Record*>(
               &_Record_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Record& a, Record& b) {
    a.Swap(&b);
  }
  inline void Swap(Record* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Record* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Record* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Record>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Record& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Record& from) {
    Record::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Record* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Record";
  }
  protected:
  explicit Record(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLegalAddressFieldNumber = 2,
    kNameOrganizationFieldNumber = 3,
    kActivityTypeFieldNumber = 4,
    kCreationYearFieldNumber = 1,
    kActivityForeignEconomicFieldNumber = 5,
  };
  // required string legalAddress = 2;
  bool has_legaladdress() const;
  private:
  bool _internal_has_legaladdress() const;
  public:
  void clear_legaladdress();
  const std::string& legaladdress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_legaladdress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_legaladdress();
  PROTOBUF_NODISCARD std::string* release_legaladdress();
  void set_allocated_legaladdress(std::string* legaladdress);
  private:
  const std::string& _internal_legaladdress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_legaladdress(const std::string& value);
  std::string* _internal_mutable_legaladdress();
  public:

  // required string nameOrganization = 3;
  bool has_nameorganization() const;
  private:
  bool _internal_has_nameorganization() const;
  public:
  void clear_nameorganization();
  const std::string& nameorganization() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nameorganization(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nameorganization();
  PROTOBUF_NODISCARD std::string* release_nameorganization();
  void set_allocated_nameorganization(std::string* nameorganization);
  private:
  const std::string& _internal_nameorganization() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nameorganization(const std::string& value);
  std::string* _internal_mutable_nameorganization();
  public:

  // optional string activityType = 4;
  bool has_activitytype() const;
  private:
  bool _internal_has_activitytype() const;
  public:
  void clear_activitytype();
  const std::string& activitytype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_activitytype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_activitytype();
  PROTOBUF_NODISCARD std::string* release_activitytype();
  void set_allocated_activitytype(std::string* activitytype);
  private:
  const std::string& _internal_activitytype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_activitytype(const std::string& value);
  std::string* _internal_mutable_activitytype();
  public:

  // required int32 creationYear = 1;
  bool has_creationyear() const;
  private:
  bool _internal_has_creationyear() const;
  public:
  void clear_creationyear();
  int32_t creationyear() const;
  void set_creationyear(int32_t value);
  private:
  int32_t _internal_creationyear() const;
  void _internal_set_creationyear(int32_t value);
  public:

  // optional bool activityForeignEconomic = 5;
  bool has_activityforeigneconomic() const;
  private:
  bool _internal_has_activityforeigneconomic() const;
  public:
  void clear_activityforeigneconomic();
  bool activityforeigneconomic() const;
  void set_activityforeigneconomic(bool value);
  private:
  bool _internal_activityforeigneconomic() const;
  void _internal_set_activityforeigneconomic(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Record)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr legaladdress_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nameorganization_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr activitytype_;
    int32_t creationyear_;
    bool activityforeigneconomic_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Record_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Record

// required int32 creationYear = 1;
inline bool Record::_internal_has_creationyear() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Record::has_creationyear() const {
  return _internal_has_creationyear();
}
inline void Record::clear_creationyear() {
  _impl_.creationyear_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline int32_t Record::_internal_creationyear() const {
  return _impl_.creationyear_;
}
inline int32_t Record::creationyear() const {
  // @@protoc_insertion_point(field_get:Record.creationYear)
  return _internal_creationyear();
}
inline void Record::_internal_set_creationyear(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.creationyear_ = value;
}
inline void Record::set_creationyear(int32_t value) {
  _internal_set_creationyear(value);
  // @@protoc_insertion_point(field_set:Record.creationYear)
}

// required string legalAddress = 2;
inline bool Record::_internal_has_legaladdress() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Record::has_legaladdress() const {
  return _internal_has_legaladdress();
}
inline void Record::clear_legaladdress() {
  _impl_.legaladdress_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Record::legaladdress() const {
  // @@protoc_insertion_point(field_get:Record.legalAddress)
  return _internal_legaladdress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Record::set_legaladdress(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.legaladdress_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Record.legalAddress)
}
inline std::string* Record::mutable_legaladdress() {
  std::string* _s = _internal_mutable_legaladdress();
  // @@protoc_insertion_point(field_mutable:Record.legalAddress)
  return _s;
}
inline const std::string& Record::_internal_legaladdress() const {
  return _impl_.legaladdress_.Get();
}
inline void Record::_internal_set_legaladdress(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.legaladdress_.Set(value, GetArenaForAllocation());
}
inline std::string* Record::_internal_mutable_legaladdress() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.legaladdress_.Mutable(GetArenaForAllocation());
}
inline std::string* Record::release_legaladdress() {
  // @@protoc_insertion_point(field_release:Record.legalAddress)
  if (!_internal_has_legaladdress()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.legaladdress_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.legaladdress_.IsDefault()) {
    _impl_.legaladdress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Record::set_allocated_legaladdress(std::string* legaladdress) {
  if (legaladdress != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.legaladdress_.SetAllocated(legaladdress, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.legaladdress_.IsDefault()) {
    _impl_.legaladdress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Record.legalAddress)
}

// required string nameOrganization = 3;
inline bool Record::_internal_has_nameorganization() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Record::has_nameorganization() const {
  return _internal_has_nameorganization();
}
inline void Record::clear_nameorganization() {
  _impl_.nameorganization_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Record::nameorganization() const {
  // @@protoc_insertion_point(field_get:Record.nameOrganization)
  return _internal_nameorganization();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Record::set_nameorganization(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.nameorganization_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Record.nameOrganization)
}
inline std::string* Record::mutable_nameorganization() {
  std::string* _s = _internal_mutable_nameorganization();
  // @@protoc_insertion_point(field_mutable:Record.nameOrganization)
  return _s;
}
inline const std::string& Record::_internal_nameorganization() const {
  return _impl_.nameorganization_.Get();
}
inline void Record::_internal_set_nameorganization(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.nameorganization_.Set(value, GetArenaForAllocation());
}
inline std::string* Record::_internal_mutable_nameorganization() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.nameorganization_.Mutable(GetArenaForAllocation());
}
inline std::string* Record::release_nameorganization() {
  // @@protoc_insertion_point(field_release:Record.nameOrganization)
  if (!_internal_has_nameorganization()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.nameorganization_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nameorganization_.IsDefault()) {
    _impl_.nameorganization_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Record::set_allocated_nameorganization(std::string* nameorganization) {
  if (nameorganization != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.nameorganization_.SetAllocated(nameorganization, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nameorganization_.IsDefault()) {
    _impl_.nameorganization_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Record.nameOrganization)
}

// optional string activityType = 4;
inline bool Record::_internal_has_activitytype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Record::has_activitytype() const {
  return _internal_has_activitytype();
}
inline void Record::clear_activitytype() {
  _impl_.activitytype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Record::activitytype() const {
  // @@protoc_insertion_point(field_get:Record.activityType)
  return _internal_activitytype();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Record::set_activitytype(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.activitytype_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Record.activityType)
}
inline std::string* Record::mutable_activitytype() {
  std::string* _s = _internal_mutable_activitytype();
  // @@protoc_insertion_point(field_mutable:Record.activityType)
  return _s;
}
inline const std::string& Record::_internal_activitytype() const {
  return _impl_.activitytype_.Get();
}
inline void Record::_internal_set_activitytype(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.activitytype_.Set(value, GetArenaForAllocation());
}
inline std::string* Record::_internal_mutable_activitytype() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.activitytype_.Mutable(GetArenaForAllocation());
}
inline std::string* Record::release_activitytype() {
  // @@protoc_insertion_point(field_release:Record.activityType)
  if (!_internal_has_activitytype()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.activitytype_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.activitytype_.IsDefault()) {
    _impl_.activitytype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Record::set_allocated_activitytype(std::string* activitytype) {
  if (activitytype != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.activitytype_.SetAllocated(activitytype, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.activitytype_.IsDefault()) {
    _impl_.activitytype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Record.activityType)
}

// optional bool activityForeignEconomic = 5;
inline bool Record::_internal_has_activityforeigneconomic() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Record::has_activityforeigneconomic() const {
  return _internal_has_activityforeigneconomic();
}
inline void Record::clear_activityforeigneconomic() {
  _impl_.activityforeigneconomic_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool Record::_internal_activityforeigneconomic() const {
  return _impl_.activityforeigneconomic_;
}
inline bool Record::activityforeigneconomic() const {
  // @@protoc_insertion_point(field_get:Record.activityForeignEconomic)
  return _internal_activityforeigneconomic();
}
inline void Record::_internal_set_activityforeigneconomic(bool value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.activityforeigneconomic_ = value;
}
inline void Record::set_activityforeigneconomic(bool value) {
  _internal_set_activityforeigneconomic(value);
  // @@protoc_insertion_point(field_set:Record.activityForeignEconomic)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Record_2eproto
